import { 
  UtensilsCrossed, 
  Building, 
  Laptop, 
  HeartPulse, 
  GraduationCap, 
  ShoppingBag, 
  HardHat, 
  Car, 
  CreditCard, 
  Plane, 
  Sparkles, 
  Truck,
  Users,
  Briefcase
} from 'lucide-react'

export const CATEGORY_ICONS = {
  'restaurants': UtensilsCrossed,
  'real-estate': Building,
  'technology': Laptop,
  'healthcare': HeartPulse,
  'education': GraduationCap,
  'retail': ShoppingBag,
  'construction': HardHat,
  'automotive': Car,
  'finance': CreditCard,
  'travel': Plane,
  'beauty': Sparkles,
  'logistics': Truck,
  'professional-job-seeker': Users,
  'professionals': Users,
  'hiring-company-hr': Briefcase,
  'companies': Briefcase,
  'other': Briefcase,
}

export const CATEGORY_GRADIENTS = {
  'restaurants': 'from-orange-400 to-amber-500',
  'real-estate': 'from-emerald-400 to-green-500',
  'technology': 'from-blue-400 to-cyan-500',
  'healthcare': 'from-red-400 to-pink-500',
  'education': 'from-purple-400 to-violet-500',
  'retail': 'from-pink-400 to-rose-500',
  'construction': 'from-orange-400 to-red-500',
  'automotive': 'from-teal-400 to-cyan-500',
  'finance': 'from-indigo-400 to-purple-500',
  'travel': 'from-sky-400 to-blue-500',
  'beauty': 'from-purple-400 to-pink-500',
  'logistics': 'from-lime-400 to-green-500',
  'professional-job-seeker': 'from-blue-500 to-indigo-600',
  'professionals': 'from-blue-500 to-indigo-600',
  'hiring-company-hr': 'from-sky-500 to-blue-600',
  'companies': 'from-sky-500 to-blue-600',
}

export const CATEGORY_BG_COLORS = {
  'restaurants': 'bg-gradient-to-br from-orange-50 to-amber-50',
  'real-estate': 'bg-gradient-to-br from-emerald-50 to-green-50',
  'technology': 'bg-gradient-to-br from-blue-50 to-cyan-50',
  'healthcare': 'bg-gradient-to-br from-red-50 to-pink-50',
  'education': 'bg-gradient-to-br from-purple-50 to-violet-50',
  'retail': 'bg-gradient-to-br from-pink-50 to-rose-50',
  'construction': 'bg-gradient-to-br from-orange-50 to-red-50',
  'automotive': 'bg-gradient-to-br from-teal-50 to-cyan-50',
  'finance': 'bg-gradient-to-br from-indigo-50 to-purple-50',
  'travel': 'bg-gradient-to-br from-sky-50 to-blue-50',
  'beauty': 'bg-gradient-to-br from-purple-50 to-pink-50',
  'logistics': 'bg-gradient-to-br from-lime-50 to-green-50',
  'professional-job-seeker': 'bg-gradient-to-br from-blue-50 to-indigo-50',
  'professionals': 'bg-gradient-to-br from-blue-50 to-indigo-50',
  'hiring-company-hr': 'bg-gradient-to-br from-sky-50 to-blue-50',
  'companies': 'bg-gradient-to-br from-sky-50 to-blue-50',
}
